// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD55fUIN_XuC6Wt25w9MbrtIOY6HqJPt2A',
    appId: '1:484911144322:web:1c7eb0406edda7642e839b',
    messagingSenderId: '484911144322',
    projectId: 'n2-mobile-22920',
    authDomain: 'n2-mobile-22920.firebaseapp.com',
    storageBucket: 'n2-mobile-22920.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUC-ax1bluofU2z2asWEXQqZ7LGqpmpns',
    appId: '1:484911144322:android:73c27636674549352e839b',
    messagingSenderId: '484911144322',
    projectId: 'n2-mobile-22920',
    storageBucket: 'n2-mobile-22920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAKQOgGKsNKEYD8jrwIFOyBmeC4aEALeQ',
    appId: '1:484911144322:ios:3c3f88241a40f9bd2e839b',
    messagingSenderId: '484911144322',
    projectId: 'n2-mobile-22920',
    storageBucket: 'n2-mobile-22920.appspot.com',
    iosBundleId: 'com.example.n1Mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAKQOgGKsNKEYD8jrwIFOyBmeC4aEALeQ',
    appId: '1:484911144322:ios:6f63d98f19a75df42e839b',
    messagingSenderId: '484911144322',
    projectId: 'n2-mobile-22920',
    storageBucket: 'n2-mobile-22920.appspot.com',
    iosBundleId: 'com.example.n1Mobile.RunnerTests',
  );
}
